on:
  push:
    branches: [ 'hpm-2024.05.1', 'dev/*' ]
  pull_request:

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Cache buildroot download sources
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-buildroot-dl
          path: dl
      
      - name: Download cargo-binutils
        run: |
          cargo install cargo-binutils

      - name: Build image
        run: |
          make hpmicro_hpm6360evk_defconfig
          make all

      - name: Archive image artifacts
        uses: actions/upload-artifact@v4
        with:
          name: image
          path: output/images/flash.img
            
